[versions]
injekt = "1.16.1"
kotlin = "2.0.20"
ktlint-cli = "1.3.1"
spotless = "6.25.0"

[libraries]
injekt = { module = "uy.kohesive.injekt:injekt-core", version.ref = "injekt" }

ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint-cli" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
